# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master

clone_depth: 50

# what combinations to test
environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 7
    - nodejs_version: 7.6

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install yarn -g
  - yarn install --frozen-lockfile

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - yarn --version
  - npm test
